# Generated by Django 2.2.7 on 2020-02-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0003_auto_20200218_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stimulus',
            name='stimulus_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
