# Generated by Django 2.2.7 on 2020-02-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0006_auto_20200218_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stimulus',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
