# Generated by Django 2.2.7 on 2020-04-07 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0007_auto_20200218_0535'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='form',
        #     name='condition',
        # ),
        # migrations.RemoveField(
        #     model_name='form',
        #     name='condition_matlab',
        # ),
        migrations.AlterField(
            model_name='session',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(db_column='session_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pyensemble.Session'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_order', models.PositiveSmallIntegerField(default=0)),
                ('form_question_num', models.PositiveSmallIntegerField(default=0)),
                ('question_iteration', models.PositiveSmallIntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('response_order', models.PositiveSmallIntegerField(default=0)),
                ('response_text', models.TextField(blank=True)),
                ('response_enum', models.PositiveIntegerField(blank=True, null=True)),
                ('decline', models.BooleanField(default=False)),
                ('misc_info', models.TextField(blank=True)),
                ('experiment', models.ForeignKey(db_column='experiment_id', on_delete=django.db.models.deletion.CASCADE, to='pyensemble.Experiment')),
                ('form', models.ForeignKey(db_column='form_id', on_delete=django.db.models.deletion.CASCADE, to='pyensemble.Form')),
                ('qdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.QuestionXDataFormat')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, to='pyensemble.Session')),
                ('stimulus', models.ForeignKey(db_column='stimulus_id', on_delete=django.db.models.deletion.CASCADE, to='pyensemble.Stimulus')),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='pyensemble.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentXAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(db_column='attribute_id', on_delete=django.db.models.deletion.CASCADE, to='pyensemble.Attribute')),
                ('experiment', models.ForeignKey(db_column='experiment_id', on_delete=django.db.models.deletion.CASCADE, to='pyensemble.Experiment')),
            ],
        ),
    ]
