# Generated by Django 2.2.7 on 2020-04-07 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0008_auto_20200407_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='session',
        ),
    ]
