# Generated by Django 2.2.7 on 2020-04-08 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='subject',
            field=models.ForeignKey(db_column='subject_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='pyensemble.Subject'),
        ),
    ]
