# Generated by Django 2.2.7 on 2020-04-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0004_stimulus_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionxdataformat',
            name='html_field_type',
            field=models.CharField(blank=True, default='radiogroup', max_length=10),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_enum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
