# Generated by Django 2.2.7 on 2020-04-16 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0005_auto_20200416_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='stimulus',
            field=models.ForeignKey(db_column='stimulus_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='pyensemble.Stimulus'),
        ),
    ]
