# Generated by Django 2.2.7 on 2020-04-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0006_auto_20200416_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='form_order',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='response',
            name='form_question_num',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='response',
            name='question_iteration',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_order',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
