# Generated by Django 3.1.14 on 2023-01-23 22:17

from django.db import migrations, models
import django.db.models.deletion
import pyensemble.group.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pyensemble', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('experimenter_attached', models.BooleanField(default=False)),
                ('params', models.JSONField(default=dict)),
                ('context', models.JSONField(default=pyensemble.group.models.init_session_context)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Ready'), (2, 'Running'), (3, 'Completed'), (4, 'Aborted')], default=0)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.experiment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.ticket')),
            ],
            options={
                'unique_together': {('group', 'experiment', 'ticket')},
            },
        ),
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.subject')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSessionSubjectSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Ready Server'), (2, 'Ready Client'), (3, 'Busy'), (4, 'Response Pending')], default=0)),
                ('group_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupsession')),
                ('user_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.session')),
            ],
            options={
                'unique_together': {('group_session', 'user_session')},
            },
        ),
    ]
