# Generated by Django 3.2.17 on 2023-03-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20230226_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsession',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=64),
        ),
    ]
