# Generated by Django 3.2.17 on 2023-07-01 21:25

from django.db import migrations, models
import django.db.models.deletion
import pyensemble.group.models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0015_alter_dataformat_enum_values'),
        ('group', '0005_auto_20230413_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSessionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pyensemble.group.models.groupsession_filepath)),
                ('groupsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupsession')),
            ],
            options={
                'unique_together': {('groupsession', 'file')},
            },
        ),
        migrations.CreateModel(
            name='GroupSessionFileAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_hash', models.CharField(max_length=32, unique=True)),
                ('attribute_value_double', models.FloatField(blank=True, null=True)),
                ('attribute_value_text', models.TextField(blank=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.attribute')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupsessionfile')),
            ],
        ),
    ]
