# Generated by Django 3.2.17 on 2023-07-14 16:33

from django.db import migrations, models
import pyensemble.group.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_groupsessionfile_groupsessionfileattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsessionfile',
            name='file',
            field=models.FileField(max_length=512, upload_to=pyensemble.group.models.groupsession_filepath),
        ),
    ]
