# Generated by Django 3.2.20 on 2023-11-14 20:35

from django.db import migrations, models
from django.conf import settings
import pyensemble.group.models


def use_storage():
    if settings.USE_AWS_STORAGE:
        from pyensemble.storage_backends import S3DataStorage
        storage = S3DataStorage

    else:
        from django.core.files.storage import FileSystemStorage
        storage = FileSystemStorage

    return storage

class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_groupsessionfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsessionfile',
            name='file',
            field=models.FileField(max_length=512, storage=use_storage(), upload_to=pyensemble.group.models.groupsession_filepath),
        ),
    ]
