# Generated by Django 4.2.17 on 2025-01-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0023_subject_allowed_emailverification'),
        ('group', '0009_alter_groupsessionfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(through='group.GroupSubject', to='pyensemble.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='groupsubject',
            unique_together={('group', 'subject')},
        ),
    ]
