# Generated by Django 2.2.7 on 2020-04-17 02:11

from django.db import migrations

def import_data_formats(apps, schema_editor):
    DataFormat = apps.get_model('pyensemble', 'DataFormat')

    import_formats = ['varchar','text','int16','int32','int64','double','datetime','null']

    instances = []
    for format in import_formats:
        instances.append(DataFormat(df_type=format))

    DataFormat.objects.bulk_create(instances)

class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_data_formats),
    ]
