# Generated by Django 2.2.7 on 2020-02-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='ethnicity',
            field=models.CharField(choices=[('HL', 'Hispanic or Latino'), ('NHL', 'Not Hispanic or Latino'), ('UN', 'Undeclared')], default='UN', max_length=4),
        ),
        migrations.AlterField(
            model_name='subject',
            name='race',
            field=models.CharField(choices=[('AIAN', 'American Indian or Alaska Native'), ('A', 'Asian'), ('B', 'Black or African American'), ('NHPI', 'Native Hawaiian or Other Pacific Islander'), ('W', 'White'), ('UN', 'Undeclared')], default='UN', max_length=2),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('UN', 'Undeclared')], default='UN', max_length=2),
        ),
    ]
