# Generated by Django 2.2.7 on 2020-05-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='html_field_type',
            field=models.CharField(choices=[('radiogroup', 'radiogroup'), ('checkbox', 'checkbox'), ('textarea', 'textarea'), ('text', 'text'), ('menu', 'menu'), ('numeric', 'numeric')], default='radiogroup', max_length=10),
        ),
    ]
