# Generated by Django 3.2.17 on 2023-02-11 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0002_auto_20230123_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='post_session_callback',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Time at which the notification entry was created')),
                ('scheduled', models.DateTimeField(help_text='Time for which sending of the notification is scheduled')),
                ('sent', models.DateTimeField(help_text='Time at which the notification was sent', null=True)),
                ('label', models.CharField(blank=True, help_text='Optional label for type of notification', max_length=100)),
                ('template', models.CharField(max_length=100)),
                ('context', models.JSONField()),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyensemble.experiment')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyensemble.session')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.subject')),
            ],
        ),
    ]
