# Generated by Django 2.2.7 on 2020-04-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0002_auto_20200408_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='class_field',
            new_name='attribute_class',
        ),
    ]
