# Generated by Django 2.2.7 on 2020-04-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0002_auto_20200417_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='experiment_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='experiment_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='form_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='form_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='response_table',
        ),
        migrations.RemoveField(
            model_name='question',
            name='heading_format',
        ),
        migrations.AlterField(
            model_name='question',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_category',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
