# Generated by Django 2.2.7 on 2020-02-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0002_auto_20200206_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attribute_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='location',
            field=models.FileField(upload_to=''),
        ),
    ]
