# Generated by Django 2.2.7 on 2020-05-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0003_auto_20200525_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentxform',
            name='form_handler',
            field=models.CharField(choices=[('form_generic', 'form_generic'), ('form_stimulus_s', 'form_stimulus_s'), ('form_generic_s', 'form_generic_s'), ('form_start_session', 'form_start_session'), ('form_start_session', 'form_start_session'), ('form_subject_register', 'form_subject_register'), ('form_image_s', 'form_image_s')], default='form_generic', max_length=50),
        ),
    ]
