# Generated by Django 2.2.7 on 2020-04-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0003_auto_20200417_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='encrypted_response_table',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
