# Generated by Django 3.2.17 on 2023-02-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0003_auto_20230211_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='executed_postsession_callback',
            field=models.BooleanField(default=False),
        ),
    ]
