# Generated by Django 2.2.7 on 2020-05-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0003_auto_20200424_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentxform',
            name='condition_script',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='experimentxform',
            name='stimulus_script',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='formxquestion',
            name='question_iteration',
            field=models.IntegerField(default=1),
        ),
    ]
