# Generated by Django 2.2.7 on 2020-05-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0004_auto_20200502_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='html_field_type',
            field=models.CharField(blank=True, choices=[('radiogroup', 'radiogroup'), ('checkbox', 'checkbox'), ('textarea', 'textarea'), ('text', 'text'), ('menu', 'menu')], default='radiogroup', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
    ]
