# Generated by Django 2.2.7 on 2020-04-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0004_auto_20200417_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='params',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='play_question_audio',
            field=models.BooleanField(default=False),
        ),
    ]
