# Generated by Django 3.2.17 on 2023-02-26 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0004_session_executed_postsession_callback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='session_diagnostic_script',
            new_name='session_reporting_script',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='diagnostics_data',
            new_name='reporting_data',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='date_time',
            new_name='start_datetime',
        ),
    ]
