# Generated by Django 2.2.7 on 2020-02-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0005_auto_20200218_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stimulus',
            name='file_format',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='stimulus',
            unique_together={('name', 'location')},
        ),
    ]
