# Generated by Django 3.2.17 on 2023-02-27 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0005_auto_20230227_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentxform',
            old_name='accept_response_script',
            new_name='record_response_script',
        ),
    ]
