# Generated by Django 2.2.7 on 2020-05-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0005_auto_20200505_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataformat',
            name='df_type',
            field=models.CharField(default='enum', max_length=15),
        ),
        migrations.AlterField(
            model_name='dataformat',
            name='enum_values',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='question',
            name='html_field_type',
            field=models.CharField(choices=[('radiogroup', 'radiogroup'), ('checkbox', 'checkbox'), ('textarea', 'textarea'), ('text', 'text'), ('menu', 'menu')], default='radiogroup', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='dataformat',
            unique_together={('df_type', 'enum_values')},
        ),
    ]
