# Generated by Django 2.2.7 on 2020-04-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0005_auto_20200417_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='experimentxform',
            name='break_loop_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='visit_once',
            field=models.BooleanField(default=False),
        ),
    ]
