# Generated by Django 3.2.17 on 2023-02-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0006_rename_accept_response_script_experimentxform_record_response_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='ticket',
            name='validfrom_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
