# Generated by Django 2.2.7 on 2020-04-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0006_auto_20200417_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
