# Generated by Django 2.2.7 on 2020-06-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0006_experiment_sona_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentxform',
            name='continue_button_text',
            field=models.CharField(default='Next', max_length=50),
        ),
    ]
