# Generated by Django 2.2.7 on 2020-04-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0007_auto_20200418_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='language',
            field=models.CharField(default='en', max_length=30),
        ),
    ]
