# Generated by Django 2.2.7 on 2020-04-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0007_auto_20200416_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionxdataformat',
            name='required',
        ),
        migrations.AddField(
            model_name='formxquestion',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
