# Generated by Django 3.2.17 on 2023-02-28 23:15

from django.db import migrations
from django.conf import settings

from configparser import ConfigParser


def create_sites(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Site = apps.get_model('sites', 'Site')

    # Get our current site
    site, created = Site.objects.get_or_create(pk=settings.SITE_ID)

    # Read our configuration
    config = ConfigParser()
    config.read(settings.SITE_CONFIG_FILE)

    # Get our primary domain
    domain = config['django'].get('domain')

    if not domain:
        raise ValueError(f"A 'domain' should be specified in the 'django' section of your config file ({settings.SITE_CONFIG_FILE}) for this data migration to set your site's domain. Currently set to {site.domain}")

    # Set the new domain and save        
    site.domain = domain
    site.name = domain
    site.save()

    # Create localhost
    Site.objects.get_or_create(domain='127.0.0.1', name='localhost')


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0007_auto_20230228_2214'),
    ]

    operations = [
        migrations.RunPython(create_sites),
    ]
