# Generated by Django 2.2.7 on 2020-04-18 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0008_auto_20200418_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentxform',
            old_name='condition_matlab',
            new_name='condition_script',
        ),
        migrations.RenameField(
            model_name='experimentxform',
            old_name='stimulus_matlab',
            new_name='stimulus_script',
        ),
    ]
