# Generated by Django 2.2.13 on 2020-08-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0009_auto_20200722_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned',
        ),
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.ForeignKey(db_column='subject_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='pyensemble.Subject'),
        ),
    ]
