# Generated by Django 3.2.17 on 2023-04-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0010_alter_session_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stimulus',
            name='location',
            field=models.FileField(max_length=512, upload_to=''),
        ),
    ]
