# Generated by Django 3.1.2 on 2020-10-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0010_auto_20200806_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='race',
            field=models.CharField(choices=[('AIAN', 'American Indian or Alaska Native'), ('A', 'Asian'), ('B', 'Black or African American'), ('NHPI', 'Native Hawaiian or Other Pacific Islander'), ('W', 'White'), ('UN', 'Undeclared')], default='UN', max_length=4),
        ),
    ]
