# Generated by Django 3.1.6 on 2021-04-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0011_auto_20201105_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributexattribute',
            name='unique_hash',
            field=models.CharField(default=None, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stimulusxattribute',
            name='unique_hash',
            field=models.CharField(default=None, max_length=32, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='attributexattribute',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stimulusxattribute',
            unique_together=set(),
        ),
    ]
