# Generated by Django 3.2.17 on 2023-05-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0011_alter_stimulus_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimulus',
            name='url',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='location',
            field=models.FileField(blank=True, max_length=512, upload_to=''),
        ),
    ]
