# Generated by Django 3.2.17 on 2023-05-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0012_auto_20230503_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataformat',
            name='_range_hash',
            field=models.CharField(db_column='range_hash', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dataformat',
            name='range_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='response_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='html_field_type',
            field=models.CharField(choices=[('radiogroup', 'radiogroup'), ('checkbox', 'checkbox'), ('textarea', 'textarea'), ('text', 'text'), ('menu', 'menu'), ('numeric', 'numeric'), ('slider', 'slider')], default='radiogroup', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='dataformat',
            unique_together={('df_type', 'enum_values')},
        ),
    ]
