# Generated by Django 3.2.17 on 2023-05-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0013_auto_20230509_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataformat',
            name='_range_hash',
            field=models.CharField(db_column='range_hash', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dataformat',
            name='enum_values',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
