# Generated by Django 3.2.17 on 2023-05-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0014_auto_20230523_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataformat',
            name='enum_values',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
