# Generated by Django 3.1.8 on 2021-06-18 21:40

import datetime
from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0014_auto_20210409_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='origin_sessid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='id_origin',
            field=models.CharField(choices=[('PYENS', 'PyEnsemble'), ('PRLFC', 'Prolific')], default='PYENS', max_length=12),
        ),
        migrations.AlterField(
            model_name='subject',
            name='dob',
            field=encrypted_model_fields.fields.EncryptedDateField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
