# Generated by Django 3.2.17 on 2023-07-03 19:26

from django.db import migrations, models
import django.db.models.deletion
import pyensemble.models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0015_alter_dataformat_enum_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pyensemble.models.session_filepath)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.session')),
            ],
            options={
                'unique_together': {('session', 'file')},
            },
        ),
        migrations.CreateModel(
            name='SessionFileAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_hash', models.CharField(max_length=32, unique=True)),
                ('attribute_value_double', models.FloatField(blank=True, null=True)),
                ('attribute_value_text', models.TextField(blank=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.attribute')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.sessionfile')),
            ],
        ),
    ]
