# Generated by Django 3.1.13 on 2021-12-25 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0015_auto_20210619_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True, max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='is_group',
            field=models.BooleanField(default=False, help_text='Subjects participate in groups'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tiny_code',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('master', 'Master'), ('user', 'User'), ('group', 'Group')], default='master', max_length=6),
        ),
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.subject')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'UNKNOWN'), (1, 'READY'), (2, 'RUNNING'), (3, 'COMPLETED'), (4, 'ABORTED')], default=0)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.experiment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.group')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pyensemble.ticket')),
            ],
            options={
                'unique_together': {('group', 'experiment', 'ticket')},
            },
        ),
        migrations.CreateModel(
            name='GroupSessionSubjectSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.groupsession')),
                ('user_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.session')),
            ],
            options={
                'unique_together': {('group_session', 'user_session')},
            },
        ),
    ]
