# Generated by Django 3.1.13 on 2021-12-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0016_auto_20211225_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsession',
            name='context',
            field=models.JSONField(null=True),
        ),
    ]
