# Generated by Django 3.2.20 on 2023-11-14 20:35

from django.db import migrations, models
import django.db.models.deletion
import pyensemble.models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0017_alter_sessionfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=512, upload_to=pyensemble.models.experiment_filepath)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.experiment')),
            ],
            options={
                'unique_together': {('experiment', 'file')},
            },
        ),
        migrations.CreateModel(
            name='ExperimentFileAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_hash', models.CharField(max_length=32, unique=True)),
                ('attribute_value_double', models.FloatField(blank=True, null=True)),
                ('attribute_value_text', models.TextField(blank=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.attribute')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.experimentfile')),
            ],
        ),
    ]
