# Generated by Django 3.1.14 on 2022-04-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0017_groupsession_context'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='tiny_code',
            new_name='experimenter_code',
        ),
        migrations.AddField(
            model_name='groupsession',
            name='experimenter_attached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupsession',
            name='params',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='groupsessionsubjectsession',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Ready'), (2, 'Response Pending')], default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='trial_info',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='participant_code',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='experimentxform',
            name='form_handler',
            field=models.CharField(blank=True, choices=[('form_generic', 'form_generic'), ('form_stimulus_s', 'form_stimulus_s'), ('form_generic_s', 'form_generic_s'), ('form_image_s', 'form_image_s'), ('form_feedback', 'form_feedback'), ('form_end_session', 'form_end_session'), ('form_consent', 'form_consent'), ('form_subject_register', 'form_subject_register'), ('form_subject_email', 'form_subject_email'), ('group_trial', 'group_trial')], default='form_generic', max_length=50),
        ),
        migrations.AlterField(
            model_name='groupsession',
            name='context',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='groupsession',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Ready'), (2, 'Running'), (3, 'Completed'), (4, 'Aborted')], default=0),
        ),
        migrations.AlterField(
            model_name='groupsession',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyensemble.ticket'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
    ]
