# Generated by Django 3.1.14 on 2022-09-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0018_auto_20220418_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentxform',
            name='use_clientside_validation',
            field=models.BooleanField(default=False),
        ),
    ]
