# Generated by Django 3.2.25 on 2024-10-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0019_auto_20231115_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='params',
            field=models.JSONField(null=True),
        ),
    ]
