# Generated by Django 3.2.25 on 2024-11-15 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0020_study_params'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyxexperiment',
            options={'ordering': ['experiment_order']},
        ),
        migrations.AddField(
            model_name='study',
            name='experiments',
            field=models.ManyToManyField(through='pyensemble.StudyXExperiment', to='pyensemble.Experiment'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyensemble.attribute'),
        ),
    ]
