# Generated by Django 5.2 on 2025-05-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0024_alter_experimentxform_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='callback_for_dispatch',
            field=models.CharField(blank=True, help_text='Optional callback function to use to send the notification', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='ethnicity',
            field=models.CharField(choices=[('NHL', 'Not Hispanic or Latino'), ('HL', 'Hispanic or Latino'), ('UN', 'Undeclared')], default='UN', max_length=4),
        ),
        migrations.AlterField(
            model_name='subject',
            name='race',
            field=models.CharField(choices=[('AIAN', 'American Indian or Alaska Native'), ('A', 'Asian'), ('NHPI', 'Native Hawaiian or Other Pacific Islander'), ('B', 'Black or African American'), ('W', 'White'), ('MTOR', 'More than One Race'), ('UN', 'Undeclared')], default='UN', max_length=4),
        ),
    ]
