# Generated by Django 5.2 on 2025-06-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyensemble', '0025_notification_callback_for_dispatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='form_served',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
